version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      # Allow Jenkins to run Docker commands on the host (optional; required if you plan to build/run containers inside Jenkins)
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home: